"""add webauthn table for passkeys

Revision ID: d110576772a4
Revises: a10264213789
Create Date: 2026-02-01 09:46:21.412418

"""
from alembic import op
import flask_security
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd110576772a4'
down_revision = 'a10264213789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_authn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(length=1024), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', flask_security.datastore.AsaList(), nullable=True),
    sa.Column('backup_state', sa.Boolean(), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('extensions', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('lastuse_datetime', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('usage', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_web_authn_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_authn'))
    )
    with op.batch_alter_table('web_authn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_authn_credential_id'), ['credential_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_authn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_authn_credential_id'))

    op.drop_table('web_authn')
    # ### end Alembic commands ###
